filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/dockerlogs/*/*.log
  include_lines: ["INGEST_TO_ES", "Incoming"]

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  
setup.kibana:
  host: "elk:5601"

output.elasticsearch:
  hosts: ["elk:9200"]
  #index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
  pipelines:
    - pipeline: mutating_filebeat_log
      when.contains:
        message: "INGEST_TO_ES"
  indices:
    - index: "cinemas"
      when.contains:
        message: "INGEST_TO_ES"
    - index: "movies"
      when.contains:
        message: "Incoming"

logging.metrics.enabled: false