service: movies-service

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1

package:
  exclude:
    - "**/*.ts"
    - "test/**"
    - "scripts/**"
    - ".vscode/**"
    - "node_modules/**"
    - "*"
    - "!package.json"

functions:
  hello-get:
    handler: dist/src/lambda.http
    events:
      - http:
          path: /api/hello
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                greeting: true
  goodbye-post:
    handler: dist/src/lambda.http
    events:
      - http:
          path: /api/goodbye/{postId}
          method: post
          cors: true
          request:
            parameters:
              paths:
                postId: true
  other:
    handler: dist/src/lambda.http
    events:
      - http: ANY /
      - http: ANY /{proxy+}