# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # movies service
      - restore_cache:
          name: movies service restore cache
          keys:
            - v1-dependencies-{{ checksum "movies-service/package.json" }}

      - run:
          name: movies service temporary remove .git from oas-tools
          command: rm -rf /home/circleci/repo/movies-service/node_modules/oas-tools/.git
          working_directory: movies-service

      - run: 
          name: movies service npm install 
          command: npm install
          working_directory: movies-service

      - save_cache:
          name: movies service save cache
          paths:
            - movies-service/node_modules
          key: v1-dependencies-{{ checksum "movies-service/package.json" }}

      - run:
          name: movies service lint
          command: npm run lint
          working_directory: movies-service

      - run:
          name: movies service test
          command: npm run test
          working_directory: movies-service