filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/dockerlogs/*/*.log
  include_lines: ["ingest_to_index_cinemas", "Incoming"]
  close_inactive: 1m
  ignore_older: 2m
  clean_inactive: 5m

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  
setup.kibana:
  host: "elk:5601"

output.elasticsearch:
  hosts: ["elk:9200"]
  pipelines:
  - pipeline: mutating_filebeat_log
    when.contains:
      message: "ingest_to_index_cinemas"
  indices:
    - index: "cinemas"
      when.contains:
        message: "ingest_to_index_cinemas"
    - index: "movies"
      when.contains:
        message: "Incoming"

logging.metrics.enabled: false