openapi: 3.0.0
info:
  title: Cinemas API
  description: Cinemas API.
  version: '1.0'

paths:
  /search/ingest:
    post:
      x-swagger-router-controller: searchRoute
      operationId: ingestCinemas
      tags:
        - /search
      description: >-
        search cinema
      requestBody:
        description: Elastic Search Query
        x-name: search
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnyValue'
      responses:
        '200':
          description: Successful request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hello'
        default:
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSummary'
  /search:
    get:
      x-swagger-router-controller: searchRoute
      operationId: searchCinema
      tags:
        - /search
      description: >-
        search cinema
      requestBody:
        description: Elastic Search Query
        x-name: search
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnyValue'
      responses:
        '200':
          description: Successful request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hello'
        default:
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSummary'

servers:
  - url: '/api'
components:
  schemas:
    ErrorSummary:
      properties:
        message:
          type: string
        error:
          $ref: '#/components/schemas/Errors'
      required:
        - message
    Errors:
      type: array
      items:
        $ref: '#/components/schemas/ErrorDetail'
    ErrorDetail:
      type: object
      properties:
        code:
          type: string
        params:
          type: string
        message:
          type: string
        path:
          type: string
    AnyValue:
      nullable: true
      description: Can be anything, including null.          
    Hello:
      properties:
        msg:
          type: string
      required:
        - msg
